language: c

sudo: true

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - iputils-ping
compiler:
    - gcc

script:
    - ./autogen.sh
    - ./configure
    - make uninstalled
    - bash test/ssh.sh
    - bash test/ci/001/test.sh
