language: c

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

compiler:
    - gcc

script:
    - make get-deps
    - make build-deps
    - make -C ./example/client
