language: c

sudo: true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq valgrind

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - iputils-ping

compiler:
    - gcc

script:
    - ./autogen.sh
    - ./configure
    - make uninstalled
    - bash test/all.sh
