language: c

sudo: true

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - iputils-ping
            - valgrind
compiler:
    - gcc

script:
    - ./autogen.sh
    - ./configure
    - make uninstalled
    - bash test/all.sh
